# Generated by Django 5.0.6 on 2024-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
