# Generated by Django 5.0.6 on 2024-06-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_userfollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
