# Generated by Django 5.0.6 on 2024-06-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userfollows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
